Rick:
  provider: facebook
  uid: '100004263903117'
  info:
    email: cagklcv_wongsen_1345778097@tfbnw.net
    name: Rick Amdbfcijcaag Wongsen
  credentials:
    token: AAAG6cnTDdHUBAEQCFaacWYmCmN4DRHkJLiYjLjnVh2I2Q7swf8JoaJtATq5Ns8M1jwmZB1qPiCBjc7TsHZBBBg1fltsRlaEptnHenQSehACkhfjQAu
    expires_at: 9999999999
# {"provider"=>"facebook",
#  "uid"=>"100004263903117",
#  "info"=>
#   {"email"=>"cagklcv_wongsen_1345778097@tfbnw.net",
#    "name"=>"Rick Amdbfcijcaag Wongsen",
#    "first_name"=>"Rick",
#    "last_name"=>"Wongsen",
#    "image"=>"http://graph.facebook.com/100004263903117/picture?type=square",
#    "urls"=>
#     {"Facebook"=>"http://www.facebook.com/profile.php?id=100004263903117"}},
#  "credentials"=>
#   {"token"=>
#     "AAAG6cnTDdHUBALIvEDRkoClWbYETRq1X4UqfvOEeGrb77GF8B3I8ZBzOn2JmOMMmZAFr13Xi8d5rLGyWEyp9Oq2HZCmo3ZBhGaXyRDbTlvnxKr24xLRZA",
#    "expires_at"=>1345784403,
#    "expires"=>true},
#  "extra"=>
#   {"raw_info"=>
#     {"id"=>"100004263903117",
#      "name"=>"Rick Amdbfcijcaag Wongsen",
#      "first_name"=>"Rick",
#      "middle_name"=>"Amdbfcijcaag",
#      "last_name"=>"Wongsen",
#      "link"=>"http://www.facebook.com/profile.php?id=100004263903117",
#      "gender"=>"male",
#      "email"=>"cagklcv_wongsen_1345778097@tfbnw.net",
#      "timezone"=>0,
#      "locale"=>"en_US",
#      "updated_time"=>"2012-08-24T03:15:01+0000"}}}